name: build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -r .latexmkrc

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Notes_on_Probability_Theory_and_Stochastic_Processes
          path: Notes_on_Probability_Theory_and_Stochastic_Processes.pdf
          retention-days: 30

      - name: Create or Update Latest Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "Notes_on_Probability_Theory_and_Stochastic_Processes.pdf"
          tag: "latest"
          name: "Latest Build"
          body: "This is an automated build from the latest commit on the main branch. Updated on ${{ github.event.head_commit.timestamp }}."
          prerelease: true